DEFAULT_LEAD_TIME_DAYS: int = 7
DEFAULT_REORDER_LEVEL: int = 10
DEFAULT_DISCOUNT_PERCENT: float = 0.0
DEFAULT_STOCK_QUANTITY: int = 0
DEFAULT_QUANTITY_RECEIVED: int = 0
DEFAULT_TOTAL_AMOUNT: float = 0.0
